### ISSUE TITLE
Translation of Mods

### ISSUE THREAD

**Issue by CarstenG** [SanchozzDeponianin/ONIMods#10]
Do you accept Pull Requests with translations of Mods? In my case I would like to add the German translation of the Carousel. Thanks!

**Comment by SanchozzDeponianin** [comment]
sorry I didn't answer for a long time. I was ill and was treated in the hospital.

yes, I accept pull requests with translations of mods.

**Comment by CarstenG** [comment]
Hope, you are better now.
Where should I add my de.po file? In sub directory "Mods" or "src"?

**Comment by SanchozzDeponianin** [comment]
both

**Comment by SanchozzDeponianin** [comment]
Thank you for contributing new translations.
