### ISSUE TITLE
[issue] Butcher station crashing in vanilla ONI since 9.12.2021

### ISSUE THREAD

**Issue by pnowojski** [SanchozzDeponianin/ONIMods#13]
Butcher station crashing in vanilla ONI since 9.12.2021. After crash butcher station and two other mods are highlighted as the likely cause (insulated airlocks and insulated high watt link), but those other two are working fine after disabling the butcher station mod.

## Expected Behavior

Game is crashing before reaching main menu. Please check the [Player.log](https://gist.github.com/pnowojski/c4ea876b02b744177a3836c47b565180). I don't have Spaced Out! DLC, I'm not using any preview branches.

## Current Behavior

Game is crashing before reaching main menu. Game started to crash on 9.12.2021 after some ONI update was downloaded.

## Mod Versions

1.5.1, Steam subscription. I haven't tried mod updater, but other users in steamworkshop reported that it didn't help.

## Steps to Reproduce

1. enable the mod
2. start the game

**Comment by SanchozzDeponianin** [comment]
I don't see [Mod Updater](https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283) in the list of your mods. Use it first.

**Comment by pnowojski** [comment]
Hmm, thanks for the tip and sorry for spamming. After using Mod Updater it seemed to work. I got mislead by other comments in the steamworkshop.
