### ISSUE TITLE
maybe a bug of Fishing Station

### ISSUE THREAD

**Issue by Ventulus-lab** [SanchozzDeponianin/ONIMods#19]
In your mod Fishing Station,"Babies and Morbs cannot be butched",so in the critter filter there is no baby fish to choose.
This station'status   shows how many critters are stored. If there are only adult fish in the room below, then the fish can be caught and the number displayed normally. If there is a mix of adult and baby fish in the room below, then the number displayed will be incorrect and the fish will not be caught correctly.(maybe because the number of critters is include babys,the "Auto-Wrangle Surplus" feature of your mod does not show   the number of adult fish you have counted, nor does it refresh the number of fish in the room after you kill them, so the player has to save and load.)

I found this mainly because the game doesn't have a self-contained building that can filter and catch   fish. I would use your building to differentiate between baby and adult fish, rather than killing for meat.

**Comment by SanchozzDeponianin** [comment]
This is not a bug. Counting the number of creatures in the room by both stations is carried out absolutely as well as by the Critter Drop-Off.

Also, need to remember that the game applies the "Overcrowded" debuff to the creatures, taking into account the presence of children.

In principle, I could make an additional checkbox to take into account or not to take into account children when counting the number of creatures.

**Comment by Ventulus-lab** [comment]
@SanchozzDeponianin 
Please add this feature to your mod that you said "an additional checkbox to take into account or not to take into account children" . It seems that it has not been added in the current version.
In fact, it would be nice if you could design the mod's functionality specifically for this requirement. I would like two fish ponds. One is a nursery: the eggs hatch into baby fish, and when the baby fish grow up there is a building that transfers them to the other fish pond. In the other pond are adult fish, they lay eggs, grow old and turn into fish meat. The eggs  laid can be transported back to the nursery on a rail.
The state "Overcrowded" doesn't really matter. Because with these two sub-pools, the player knows exactly how big the pond is and the maximum number of fish it can hold, and if there are more, they are killed and eaten for meat. And even if the baby fish are crowded, it doesn't affect  growing into adults.

**Comment by SanchozzDeponianin** [comment]
@Ventulus-lab 
I will add this feature in the next version of the mod.
when the Klei will release a new version of the game.
in the meantime, you can translate new strings
```
#. ButcherStation.STRINGS.OPTIONS.ENABLE_NOT_COUNT_BABIES.NAME
msgctxt "ButcherStation.STRINGS.OPTIONS.ENABLE_NOT_COUNT_BABIES.NAME"
msgid "Enable \"Don't count Babies\" Feachure"
msgstr ""

#. ButcherStation.STRINGS.UI.UISIDESCREENS.BUTCHERSTATIONSIDESCREEN.NOT_COUNT_BABIES.NAME
msgctxt "ButcherStation.STRINGS.UI.UISIDESCREENS.BUTCHERSTATIONSIDESCREEN.NOT_COUNT_BABIES.NAME"
msgid "Don't count Babies"
msgstr ""

#. ButcherStation.STRINGS.UI.UISIDESCREENS.BUTCHERSTATIONSIDESCREEN.NOT_COUNT_BABIES.TOOLTIP
msgctxt "ButcherStation.STRINGS.UI.UISIDESCREENS.BUTCHERSTATIONSIDESCREEN.NOT_COUNT_BABIES.TOOLTIP"
msgid "Babies will not be counted when counting the number of Critters in the Room"
msgstr ""
```

**Comment by Ventulus-lab** [comment]
#. ButcherStation.STRINGS.OPTIONS.ENABLE_NOT_COUNT_BABIES.NAME
msgctxt "ButcherStation.STRINGS.OPTIONS.ENABLE_NOT_COUNT_BABIES.NAME"
msgid "Enable \"Don't count Babies\" Feachure"
msgstr "启用“不算幼崽”功能"

#. ButcherStation.STRINGS.UI.UISIDESCREENS.BUTCHERSTATIONSIDESCREEN.NOT_COUNT_BABIES.NAME
msgctxt "ButcherStation.STRINGS.UI.UISIDESCREENS.BUTCHERSTATIONSIDESCREEN.NOT_COUNT_BABIES.NAME"
msgid "Don't count Babies"
msgstr "不算幼崽"

#. ButcherStation.STRINGS.UI.UISIDESCREENS.BUTCHERSTATIONSIDESCREEN.NOT_COUNT_BABIES.TOOLTIP
msgctxt "ButcherStation.STRINGS.UI.UISIDESCREENS.BUTCHERSTATIONSIDESCREEN.NOT_COUNT_BABIES.TOOLTIP"
msgid "Babies will not be counted when counting the number of Critters in the Room"
msgstr "当计算房间内小动物数量时，幼崽不会被算在内"

**Comment by SanchozzDeponianin** [comment]
Thanks for the translation.
If you want to try out a new feature now, you can [download the release for the beta version](https://github.com/SanchozzDeponianin/ONIMods/releases/tag/2022-09-24) of the game.
Just need to keep in mind that during the beta test, everything can suddenly break down when Klei publish a new patch.

**Comment by Ventulus-lab** [comment]
ok,thanks
