### ISSUE TITLE
Shown as incompatible

### ISSUE THREAD

**Issue by kuxynator** [SanchozzDeponianin/ONIMods#22]
![image](https://user-images.githubusercontent.com/66268429/160033802-75897b8b-4dc4-4cb9-8ab4-d77749fb456c.png)
![image](https://user-images.githubusercontent.com/66268429/160033879-91727a15-193a-4613-a27e-40812e4456ca.png)

BTW Thanks for you time creating ONI mods :-)

**Comment by SanchozzDeponianin** [comment]
In fact, Biological Cargo Bay exists only in the base game, and does not exists in DLC.
Therefore, there is no reason to make this mod compatible with DLC.
By the way, compatibility is indicated in the description in the steam workshop
![Снимок экрана от 2022-03-25 11-21-20_](https://user-images.githubusercontent.com/73459473/160059688-7429b9da-7847-433f-9fb2-619843abe15a.png)
