### ISSUE TITLE
Constant game crashing with mod

### ISSUE THREAD

**Issue by Th1EF-Rafas** [SanchozzDeponianin/ONIMods#23]
I've been playing new game since new update, and it was fine for 300+ cycles, but then game kept crashing during one particular cycle (few days ago)

Logs first showed somewhere an error around Cryo egg preservation mod, but fully uninstalling it didnt help. After that logs never showed anything noteworthy to pinpoint the mod causing the crash
 I have no proof per se, but I went through ALL mods 1 by 1 (figuratively of course) and managed to find the only mod, that while active does crash the game: Worn Suit doesn't drop Canister

Sadly, I had separate save file for the start of the cycle before crash, but I just have deleted it for some reason. But I have several dump save files (if it's of any help), and the last one should be the one, where this mod is the only active one
[SimDLL_CRASH_preview_506365_20220510.zip](https://github.com/SanchozzDeponianin/ONIMods/files/8675429/SimDLL_CRASH_preview_506365_20220510.zip)
(Latest MOD steam version with force update)

Steps to Reproduce:
Launch game
Wait for a while

**Comment by rigerc** [comment]
Can confirm - playing on the current public test branch it kept crashing until disabling this mod.

**Comment by SanchozzDeponianin** [comment]
the problem is found and fixed ae8d8700597428888f8c82feed9c766e66e8063f
