### ISSUE TITLE
BadReadException: bad read of entry archived_versions/preview/ButcherStation.dll from compressed archive.

### ISSUE THREAD

**Issue by HandelSarabande** [SanchozzDeponianin/ONIMods#24]
After ONI update from 2th of June 2022 game crashes with the following:

BadReadException: bad read of entry archived_versions/preview/ButcherStation.dll from compressed archive.

Ionic.Zip.ZipEntry._CheckRead (System.Int32 nbytes) (at <c5d6b36976e845b59baec1498be897f9>:0)
Ionic.Zip.ZipEntry.ExtractOne (System.IO.Stream output) (at <c5d6b36976e845b59baec1498be897f9>:0)
Ionic.Zip.ZipEntry.InternalExtract (System.String baseDir, System.IO.Stream outstream, System.String password) (at <c5d6b36976e845b59baec1498be897f9>:0)
Ionic.Zip.ZipEntry.Extract (System.IO.Stream stream) (at <c5d6b36976e845b59baec1498be897f9>:0)
KMod.ZipFile.CopyTo (System.String path, System.Collections.Generic.List`1[T] extensions) (at <b2059d57da244ebc9fb8d55e7bbaa6c7>:0)
KMod.Mod.Install () (at <b2059d57da244ebc9fb8d55e7bbaa6c7>:0)
KMod.Manager.Install (KMod.Mod mod) (at <b2059d57da244ebc9fb8d55e7bbaa6c7>:0)
KMod.Manager.Subscribe (KMod.Mod mod, System.Object caller) (at <b2059d57da244ebc9fb8d55e7bbaa6c7>:0)
KMod.Steam.UpdateMods (System.Collections.Generic.IEnumerable`1[T] added, System.Collections.Generic.IEnumerable`1[T] updated, System.Collections.Generic.IEnumerable`1[T] removed, System.Collections.Generic.IEnumerable`1[T] loaded_previews) (at <b2059d57da244ebc9fb8d55e7bbaa6c7>:0)
SteamUGCService.Update () (at <b2059d57da244ebc9fb8d55e7bbaa6c7>:0)

Build: U42-509629-S

**Comment by SanchozzDeponianin** [comment]
Obviously your steam client downloaded the files wryly. 
Just do the verification of the game files.
