### ISSUE TITLE
Manual Installation

### ISSUE THREAD

**Issue by ElectronicsArchiver** [SanchozzDeponianin/ONIMods#26]
<br>
<br>

<div align = center>

I've found that multiple GitHub ONI mod repositories 
were describing how to manually install mods, 
so I made a guide instead.

[Installation Guide]

Would you mind if I made a PR, replacing 
the local section with a link to the guide?

</div>

<br>
<br>

[Installation Guide]: https://github.com/OpenModding/Installation/tree/main/Games/Oxygen%20Not%20Included

**Comment by SanchozzDeponianin** [comment]
I don't see the point.

in addition, some repositories (such as mine) have some nuances, which may make the installation process slightly different from others.
