### ISSUE TITLE
[Issue] [WornSuitDischarge] Atmo suits keep releasing oxygen bottle

### ISSUE THREAD

**Issue by mereth** [SanchozzDeponianin/ONIMods#28]
## Expected Behavior

When a duplicant pass the atmo checkpoint and drop a worn atmo suit, an oxygen bottle shouldn't be dropped anymore, but the oxygen should refill an atmo station.

## Current Behavior

The wanted behaviour is erratic and an oxygen bottle is dropped most of the time in my current world. I was unable to reproduce it on a sandbox world and it seems to not always happen.

## Mod Versions

1.1.2, via steam subscription, up-to-date dll.

## Steps to Reproduce

With the included game save, send Joshua back to the atmo stations room.

[Player.log](https://github.com/SanchozzDeponianin/ONIMods/files/9903198/Player.log)
[save.zip](https://github.com/SanchozzDeponianin/ONIMods/files/9903214/save.zip)

**Comment by SanchozzDeponianin** [comment]
Thank you for the file provided.
it helped to better understand what was happening.
Now I have every reason to believe that the game incorrectly calculates the effect of the "Suit Sustainability Training" perk on the durability of the Suit.
Therefore, I will have to turn off the check for the presence of this perk, when predicting the breakdown of the Suit and making a decision about the discharge it.
beac4ddbfdd08ae5d40027a780a8a8160d589716
