### ISSUE TITLE
[Suit Recharger] Chore loop

### ISSUE THREAD

**Issue by MegaJani** [SanchozzDeponianin/ONIMods#31]
## Current Behavior
If a dupe runs out of air during downtime and is currently trying to use the toilet, the suit recharger chore will repeatedly interrupt the bathroom chore and locks the dupe in place, leading to a suffocation-starvation-exhaustion loop.

## Mod Versions
Newest version, using Mod Updater

## Steps to Reproduce
1. During downtime
2. Suit air tank runs out as 2.5 Going to the bathroom
3. Dupe themselves running out of air while on the toilet, so needs to take the helmet off and stop any chore
4. Breath regained, start new toilet chore
5. Repeat (since their bladder is at 100%, they will be stuck in this loop indefinitely, regardless of downtime, it onyl needs to initiate it)

A possible solution would be to move the recharge chore to be a personal need and/or increasing the priority.

**Comment by SanchozzDeponianin** [comment]
Please provide me with your save file when this happens.

**Comment by MegaJani** [comment]
Here you go: https://drive.google.com/drive/folders/1LPMZhj3geeIAp9hOiql1_tsHKx27Y1AY?usp=share_link

Although heavily modded, none of them seem to conflict to cause the issue.

**Comment by SanchozzDeponianin** [comment]
strange, I can't reproduce it.
Marie successfully manages to use the toilet before she needs to regain her breath.
![457140_20230122215546_1](https://user-images.githubusercontent.com/73459473/213926612-15d3a3a9-6255-4f83-85f8-e4b15935f800.png)
![457140_20230122215614_1](https://user-images.githubusercontent.com/73459473/213926620-b3b0ffe4-6336-47c3-a24e-f33662d239d3.png)

Also a question. These rechargers were connected to oxygen by some kind of modding pipe ? or are they not connected ?
![457140_20230122215642_1](https://user-images.githubusercontent.com/73459473/213926641-b4e6d571-7e07-45c0-b332-850d0b5de86d.png)

However, I already have thoughts on improving the priority of super urgent charging.

**Comment by MegaJani** [comment]
Yes, I use the high pressure pipes mod to connect them, that's no problem.
I noticed that sometimes they make it in time (mostly when they run out exactly as they go to the bathroom, but it's these instances when things align precisely to lock a dupe that are mildly annoying.

I thought of making a suggestion to configure the recharge threshold percentage, but that might not solve the conflicting chores if they reach that in downtime.

**Comment by MegaJani** [comment]
Hi!
I managed to capture one where I don't forget to check the priorities: https://drive.google.com/drive/folders/1LPMZhj3geeIAp9hOiql1_tsHKx27Y1AY?usp=share_link

**Comment by SanchozzDeponianin** [comment]
before I upload the [new version](https://github.com/SanchozzDeponianin/ONIMods/releases/tag/SuitRechargerTest) to the workshop.
can you test it locally ?

**Comment by MegaJani** [comment]
Gladly.
I see, it's grouped with "recover breath" now, and so it's immediate. Nice fix!

Although one dupe tried to eat while their oxygen was just "low", not empty, and they were picking up food endlessly.
I don't know if there's any spaghetti code in the game's logic, but I think it would be best to just make the regular "recharge equipment" chore an involuntary action as well, they stop their regular chores for it anyway. Downtime can wait a bit.

**Comment by SanchozzDeponianin** [comment]
Hi.
I have seen your recent posts in the unofficial ONI discord.
So, definitely, your Chore loop problem is not caused by my mod.
