### ISSUE TITLE
[butcher&fishing station] ArgumentOutOfRangeException Parameter name: index

### ISSUE THREAD

**Issue by devent** [SanchozzDeponianin/ONIMods#32]
Unknown, just an error.

`ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

System.ThrowHelper.ThrowArgumentOutOfRangeException (System.ExceptionArgument argument, System.ExceptionResource resource) (at <695d1cc93cca45069c528c15c9fdd749>:0)
System.ThrowHelper.ThrowArgumentOutOfRangeException () (at <695d1cc93cca45069c528c15c9fdd749>:0)
RanchStation+Instance.ValidateTargetRanchables () (at <1726ad14e928409087f7fe566b21e0ff>:0)
(wrapper dynamic-method) RanchStation+Instance.RanchStation+Instance.FindRanchable_Patch0(RanchStation/Instance,object)
RanchStation+<>c.<InitializeStates>b__5_1 (RanchStation+Instance smi, System.Single dt) (at <1726ad14e928409087f7fe566b21e0ff>:0)
BucketUpdater`1[DataType].Update (DataType data, System.Single dt) (at <fa50cdddb14a483d94f547557a674a42>:0)
UpdateBucketWithUpdater`1[DataType].Update (System.Single dt) (at <fa50cdddb14a483d94f547557a674a42>:0)
StateMachineUpdater+BucketGroup.AdvanceOneSubTick (System.Single dt) (at <fa50cdddb14a483d94f547557a674a42>:0)
StateMachineUpdater.AdvanceOneSimSubTick () (at <fa50cdddb14a483d94f547557a674a42>:0)
Game.SimEveryTick (System.Single dt) (at <1726ad14e928409087f7fe566b21e0ff>:0)
(wrapper dynamic-method) Game.Game.Update_Patch2(Game)

Build: U44-537329-V`

**Comment by SanchozzDeponianin** [comment]
This is the issue of the base game, not my mod.
https://forums.kleientertainment.com/klei-bug-tracker/oni/validatetargetranchables-argumentoutofrangeexception-index-r38019/
https://forums.kleientertainment.com/klei-bug-tracker/oni/crash-to-desktop-in-new-test-build-r37961/

> A developer has marked this issue as fixed. This means that the issue has been addressed in the current development build and will likely be in the next update.
