### ISSUE TITLE
Recharge station isn't used

### ISSUE THREAD

**Issue by Soaryn** [SanchozzDeponianin/ONIMods#33]
Placed down a suit recharger to start my endeavors of having a forever live in bubble suit life style... seemingly the one atmo suit user I have, will not use the charger. Even if the dock is disabled.

## Expected Behavior
The station should be used when air / charging is required.
DLC is enabled and a few other mods are included, but nothing really dealing with pathfinding or suits.

## Mod Versions
Latest as of February 17th 2023. Using mod manager in game.

**Comment by Soaryn** [comment]
They did finally go to use it! But the priorities of it are lower than the checkpoint. So there may be still something to investigate

**Comment by Soaryn** [comment]
As a follow up, they are actively unaware of the existence of the recharge station. If I disable the checkpoint for the suit dock, they prefer to run out of oxygen. Upon enabling the suit dock, they go and dock the suit, and wait for it to charge. 

Some assumptions here, is that when the tank empty, it is treating it similar to if the suit has been fully worn out. So instead of recharging they just sit there. They also seemingly have no control over the priority of this over other tasks.

**Comment by SanchozzDeponianin** [comment]
Hi, provide me with your save file.
And what is this mod with "Rayon Fiber" ?

**Comment by Soaryn** [comment]
I believe the mod is Duplicant Engineering. They seem to be using the recharge feature only if repair is turned off. (do note, that when posting this issue originally it was only the station near the suit checkpoint near the gateway printer)
[Irradiated soarynFine Cap.zip](https://github.com/SanchozzDeponianin/ONIMods/files/10781790/Irradiated.soarynFine.Cap.zip)

**Comment by SanchozzDeponianin** [comment]
it turned out that "Rayon Fiber" from "Chemical Processing", not "Dupes Engineering".
and because of him, the station can work strangely.
currently, my mod assumes that there is only one repair recipe for each type of suit. and "Chemical Processing" adds additional ones.
need a small fix.

**Comment by SanchozzDeponianin** [comment]
I uploaded the new version to the Workshop.
I also recommend adding more Batteries. the Recharger consumes a lot of energy when the repair is turned on.

**Comment by Soaryn** [comment]
Will try it out sometime this week. And I did read that the charger was 5kW when repairing which was something I was going to address to be sure it wasn't 5kJ. I assumed the former. The space area should solve most of my power needs though :P
