### ISSUE TITLE
Rebuildable AETN stopped working with latest update (QOL) [issue]

### ISSUE THREAD

**Issue by KatarinaWyatt** [SanchozzDeponianin/ONIMods#34]
The existing ones in my colony still function, the care packages still provide new neutronim cores, but selecting it to build another one just defaults to a gas pipe instead and the object no longer shows up in the build catalog.  They were behaving normally until yesterday's QOL update.

I have the DLC installed but it's disabled and I've not used it, this is a base game play through. I got the mod via Steam, I have not tried updating it since I am using the latest version.

**Comment by SanchozzDeponianin** [comment]
I uploaded the new version to steam a little more than half a day ago.
you just need to update. 
use [Mod Updater](https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283) if the game itself does not want to update the mod.
