### ISSUE TITLE
Error about Suit Recharger

### ISSUE THREAD

**Issue by LimA0LiN** [SanchozzDeponianin/ONIMods#35]
Feedback on a mistake with Suit Recharger: When people wear spacesuits and have less air left, they are in the bathroom during their time, and they repeatedly enter and exit the bathroom.
Known repair methods: Manually name people to recharge after recharging

**Comment by SanchozzDeponianin** [comment]
Hi. Please provide me with your save file and game log file  when this happens, for investigation.
log file is located at:
Windows: %userprofile%\AppData\LocalLow\Klei\Oxygen Not Included\Player.log
Mac: ~/Library/Logs/Unity/Player.log
Linux: ~/.config/unity3d/Klei/Oxygen Not Included/Player.log

**Comment by LimA0LiN** [comment]
You need to wait. I deleted save.by the way， Can you add a feature that restricts usage in rockets? Something like a dining table or washing table can be controlled by a rocket console.

**Comment by LimA0LiN** [comment]
save file:[坚不可摧的深渊.zip](https://github.com/SanchozzDeponianin/ONIMods/files/11144191/default.zip)
I hadnot found the player.log, if its important

**Comment by SanchozzDeponianin** [comment]
I see you're using the Fast Track mod.
Try to turn off the Chore Optimizations.
It seems to conflict in some way.
I will continue to see if this can be fixed somehow.
![2023-04-04 20-56-36](https://user-images.githubusercontent.com/73459473/229839919-3773b671-f803-4a77-85f2-40c707efb24e.png)

**Comment by LimA0LiN** [comment]
Can you add a feature that restricts usage in rockets? Something like a dining table or washing table can be controlled by a rocket console.
