### ISSUE TITLE
Latest update breaks "No Manual Delivery"

### ISSUE THREAD

**Issue by alexander-cg** [SanchozzDeponianin/ONIMods#36]
Latest update # 550759 - "Whatta Blast!" for game build: 046-550759-50 cause CTD

Using Spaced Out DLC with only your mod "No manual delivery" version 1.5.9  enabled, local copy, also updated through mod manager and issue persists. 

Screenshot of ONI message and attached game logs. 

![ONI CTD Msg](https://user-images.githubusercontent.com/47990587/228945952-2f22df12-2f5a-4faa-b10b-e4bcddd852e6.PNG)
[Player.log](https://github.com/SanchozzDeponianin/ONIMods/files/11115509/Player.log)

**Comment by SanchozzDeponianin** [comment]
How are you even going to update the local copy through the mod manager, lol.

I uploaded a new version of the mod to steam two weeks ago and to [github just now](https://github.com/SanchozzDeponianin/ONIMods/releases/latest). try it.
