### ISSUE TITLE
[Bug] Mess Table doesn't have no manual delivery option

### ISSUE THREAD

**Issue by Apprisco** [SanchozzDeponianin/ONIMods#38]
### Description of the bug/crash

Mess Table doesn't have a no manual delivery option, but dupes can deliver salt to it. Auto sweepers do not for some reason, as the dupe takes the errand.

### Steps To Reproduce

Build a mess table, notice it has no no manual delivery option.
![image](https://user-images.githubusercontent.com/34324909/233936157-12ef130f-f883-4445-af40-0b877864db66.png)

### Player.log

N/A

**Comment by SanchozzDeponianin** [comment]
Not a bug. It's just that no one needed such a feature. You're the first person to ask in three years.
