### ISSUE TITLE
[Issue]: the Butcher & Fishing Stations Mod Page is hidden

### ISSUE THREAD

**Issue by WoodyPampa** [SanchozzDeponianin/ONIMods#44]
### Description of the bug/crash

I just started the game to play and mod updater said that "Butcher & Fishing Stations" need to update & restart, what I did.

And like always when there is a mod update I'm looking to the mod page and read what changed etc.
But for this mod, it's weird, I can't...

It said that the Mod is Hidden or that I don't have permission to see the page Oo

And now, if I want to Load my save, even if the mod is enable in the list, all Butcher Station disappeared, with the materials they was made of.

### Steps To Reproduce

I don't know what to say, I just start the game, follow the step with Mod Updater as I always do and restarted the game, but on the workshop, the mod is listed, but I can't see the page if I clic on it

And in game in the mod updater tab, if I clic on the Steam Logo who link to the mod page, it's the same

If I try to make a research on the workshop with the keyword: Butcher or Fishing, the mod page isn't in the result.

### Player.log

[Player.log](https://github.com/SanchozzDeponianin/ONIMods/files/11969102/Player.log)

**Comment by SanchozzDeponianin** [comment]
I have no idea.
the mod is stuck in the state:

> This item is awaiting analysis by our automated content check system. It will be temporarily hidden until we verify that it does not contain harmful content (e.g. links to websites that attempt to steal information). 

it usually goes away in a couple of seconds.
probably the steam servers are buggy again.

**Comment by WoodyPampa** [comment]
I hope that it's not because of a false report against you or this mod... it's obvious that steam will found nothing but still, it's not funny for anyone.

Maybe it was just a steam servers problem like it happen sometime.

Btw the page is back, sorry for coming here and annoying you with this ^^
