### ISSUE TITLE
[Issue]: No manual delivery prevents petroleum delivery to molecular forge

### ISSUE THREAD

**Issue by Apprisco** [SanchozzDeponianin/ONIMods#47]
### Description of the bug/crash

Enable no manual delivery: super coolant production cannot continue as petroleum delivery is halted.

### Steps To Reproduce

Auto sweeper delivers fullerene and gold.
Enable no manual delivery for the molecular forge making visco gel or super coolant.
Notice that no errands can be done as petroleum is now no longer deliverable.

### Player.log

N/A

**Comment by SanchozzDeponianin** [comment]
to deliver petroleum bottles using an auto-sweeper
a) enable this checkbox in the mod settings
![457140_20230529100406_2](https://github.com/SanchozzDeponianin/ONIMods/assets/73459473/800706ae-a5f8-45d3-b9b0-dedc2b44de3e)
b) make sure that there  in the range of the auto-sweeper is a Pitcher Pump or a modded thing  that allows you to pour bottles from pipes, for example [Fluid Shipping](https://steamcommunity.com/sharedfiles/filedetails/?id=1794548334)

**Comment by Apprisco** [comment]
That's not exactly in the game. No manual delivery itself feels like a great addition to vanilla, but allowing auto sweepers to deliver liquids is simply gamebreaking.
