### ISSUE TITLE
[Issue]: Graveyard Keeper - Pips only plant sporechids

### ISSUE THREAD

**Issue by winsomniak** [SanchozzDeponianin/ONIMods#55]
### Description of the bug/crash

Pips only plant sporechids. This appears to be hard coded.

### Steps To Reproduce

Spawn in a corpse near a pip, watch it plant a sporechid

### Player.log

No crash

**Comment by SanchozzDeponianin** [comment]
Hi
make sure twice that you haven't turned off these checkboxes
![2023-10-23 20-34-38](https://github.com/SanchozzDeponianin/ONIMods/assets/73459473/020093bc-23d8-4a83-9875-8664aedbfe24)

**Comment by winsomniak** [comment]
All options were checked, mod defaults. Dupes died inside the base, I moved a pip  inside the base to handle burial. Pip would grab the body and drop a sporechid seed. Happened 4x in different parts of the base. I was planning to use this with the "duplicant lifecycles" mod but turned it off after 4 sporechids in a row.

Cool mod idea for sure. I looked at the code briefly and it seems "sporechid" is default in several contexts, so I must have hit some edge case in the mod's logic.

Cheers

**Comment by SanchozzDeponianin** [comment]
I experimented a little.
Apparently, over the past year, there have been some changes in the depths of the game, and the game no longer crashes when animals try to move the bodies of duplicants.
Now I can remove the trick of replacing the duplicant's corpse with a sporechid seed.
If Pip picked up a corpse, but then couldn't bury it properly, it should just drop it on the floor.

**Comment by winsomniak** [comment]
Nice!
