### ISSUE TITLE
[Issue]: Graveyard Keeper - Pips spawn seeds instead of planting when corpse is on constructed tiles

### ISSUE THREAD

**Issue by winsomniak** [SanchozzDeponianin/ONIMods#56]
### Description of the bug/crash

Pips spawn seeds instead of planting when corpse is located on constructed tiles,

### Steps To Reproduce

Spawn a corpse on a constructed tile near pips
Watch pip spawn in a sporechid seed

### Player.log

No log

**Comment by SanchozzDeponianin** [comment]
This is possible in a fairly narrow time range. When pip has already picked up the corpse, and carries it to the chosen burial place, and at that moment construction tiles were built in this place.
If there are no places suitable for planting plants in advance near the pip and the corpse, the pip will not even try to pick up the corpse.

Turning a corpse into a sporechid seed is such a technical trick to deceive the game. The game really does not like it when someone tries to move the body of a duplicant, and he himself is not a duplicant or a rover. The game makes a crash somewhere in the depths of the animation subsystem.
I don't want to interfere with the animation subsystem, so I use this trick.

So, I won't fix anything.
