### ISSUE TITLE
[Feature Request]: LargeTelescope Larger Range Option 

### ISSUE THREAD

**Issue by pixelkritzel** [SanchozzDeponianin/ONIMods#57]
### Description of the bug/crash

First Sorry for using the issue function but I didn't find any other way for feature requests and second thank you for making the mod.

I would welcome an option to increase the range of telescope even further, In the best case infinite but something to match the bigger clusters generated by SGT_Imalas' Cluster Generation Manager.

I know it sounds balance breaking but after over a dozen Spaced Out runs the star map exploration feels mostly like a tedious chore. 

### Steps To Reproduce

-

### Player.log

Empty file
[player..log](https://github.com/SanchozzDeponianin/ONIMods/files/13256248/player.log)

**Comment by SanchozzDeponianin** [comment]
good idea. I could add a new feature as an option.
and also for balance purposes - to make so that the further the scanned hex is, the more time it takes.

**Comment by pixelkritzel** [comment]
Sounds fair. Similar to base game.

**Comment by SanchozzDeponianin** [comment]
I did it as a [separate mod](https://steamcommunity.com/sharedfiles/filedetails/?id=3079759380).

**Comment by pixelkritzel** [comment]
Thank you!
