### ISSUE TITLE
[Issue]: Butcher & Fish Crash

### ISSUE THREAD

**Issue by VasVadum** [SanchozzDeponianin/ONIMods#60]
### Description of the bug/crash

Simply crashed when loading the game.
[ERROR] First anim file needs to be non-null. ButcherStationComplete
(First line of the first error in previous log file)

### Steps To Reproduce

Load the game?

### Player.log

[Player-prev.log](https://github.com/SanchozzDeponianin/ONIMods/files/13537761/Player-prev.log)

**Comment by SanchozzDeponianin** [comment]
After examining the log, I see that a) your game is trying to download an old version of the mod and b) the mod is semi-installed. some files are missing.
You need to reinstall the mod or update it forcibly.
Throw away the Mod Manager by Ony.
Use the [Mod Updater](https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283).
Click on this button next to the mod to force the update it.
![2023-06-16 10-11-29](https://github.com/SanchozzDeponianin/ONIMods/assets/73459473/5a66bed6-ec02-41cb-8843-2d6c2806ec1b)

**Comment by VasVadum** [comment]
The mod updater is broken.
Ony's mod manager contains an updater within it.
It shows all mods now fully up to date and has properly updated all of them except for yours I guess. Rather bizarre that it failed on one mod.
