### ISSUE TITLE
[Issue]: Description Error?

### ISSUE THREAD

**Issue by TheGrey01** [SanchozzDeponianin/ONIMods#62]
### Description of the bug/crash

Okay the issue I am having is your "description" of the requirements to build the Squirrel Wheel.  It says 200kg Wood (in game) and on steam you have 200kg Lumber, both those are technically incorrect as Lumber is not described in grams/kilograms it's described in Units (which to my knowledge is the only item described that way).  So is the requirements supposed to be 200 Units Lumber and 200 Raw Metal?

### Steps To Reproduce

No Issue: Description potentially incorrect.

### Player.log

NA

**Comment by SanchozzDeponianin** [comment]
the Klei developers themselves in the in-game database display the building requirements in kilograms for their own buildings. 
I won't even lift a finger to change my description to Units.
![457140_20231217181640_2](https://github.com/SanchozzDeponianin/ONIMods/assets/73459473/4c70f839-803b-4fa9-b2ca-9852a978c8bc)
![457140_20231217181654_2](https://github.com/SanchozzDeponianin/ONIMods/assets/73459473/ccf9aaf1-49d3-479e-9374-501b56425131)
![457140_20231217181520_2](https://github.com/SanchozzDeponianin/ONIMods/assets/73459473/f7708f73-6cd0-49e5-822c-123e4f8c6391)
