### ISSUE TITLE
[Translation]: Polish

### ISSUE THREAD

**Issue by Bzhydack** [SanchozzDeponianin/ONIMods#65]
### What mod is that translation for?

Smelter

### Additional Comments

I made Polish Translation, maybe its working.

I also have two suggestions about mod:
1. Can we get melting Plastic to Naphta Recipe in Glass Forge?
2. Can you add Melt Sulfur to Liquid Sulfur Recipe?

### translation file

[polish translation.zip](https://github.com/SanchozzDeponianin/ONIMods/files/14070173/polish.translation.zip)

**Comment by SanchozzDeponianin** [comment]
Thank you for contributing
