### ISSUE TITLE
[Issue]: Rebuildable AETN, workers dont pick neutronium cores NOT dropped from natural AETN

### ISSUE THREAD

**Issue by Glitch-ONI** [SanchozzDeponianin/ONIMods#70]
### Description of the bug/crash

I have several neutronium cores in my base, but the workers only use those which dropped from AETNs in the world.
Those from care package are not being used.

### Steps To Reproduce

simply doesnt work

### Player.log

no crash

**Comment by SanchozzDeponianin** [comment]
Show me a screenshot.

**Comment by Glitch-ONI** [comment]
![20240630162425_1](https://github.com/SanchozzDeponianin/ONIMods/assets/174152375/3d0faff5-9594-415c-9eb0-aecdaf555669)

Btw...I deactivated all mods to make sure its not another mod interfering.

**Comment by Glitch-ONI** [comment]
nvm...I didnt see that the neutronium cores from the care package have to go through the analyzer first -.-

Mod works^^

**Comment by MrPurple6411** [comment]
hrmmmm Mine however went through the analyzer just fine but still they wont build the stupid AETN. They are only moved that close to the thing because I made my dupes manually move them there to be shown in the picture.

![OxygenNotIncluded_C9UyAXj8qQ](https://github.com/user-attachments/assets/d2598f99-2691-4a2e-9125-929c06919532)
![OxygenNotIncluded_dNLTYcXcZT](https://github.com/user-attachments/assets/7ccf902f-6a43-45e8-a2f0-597114cd1efb)

**Comment by SanchozzDeponianin** [comment]
@MrPurple6411 attach your save file and the log.

**Comment by MrPurple6411** [comment]
Log: 
[Player.log](https://github.com/user-attachments/files/16368296/Player.log)

Zipped Save: 
[Lucky Galaxy.zip](https://github.com/user-attachments/files/16368298/Lucky.Galaxy.zip)

Workshop mod list file: 
[appworkshop_457140.zip](https://github.com/user-attachments/files/16368313/appworkshop_457140.zip)

**Comment by SanchozzDeponianin** [comment]
@MrPurple6411  you using this mod: https://steamcommunity.com/sharedfiles/filedetails/?id=2963257205

That's the problem. The cores are too cold, set a value from -250C, for example.
![351601030-7ccf902f-6a43-45e8-a2f0-597114cd1efb](https://github.com/user-attachments/assets/e76521c5-fc71-49be-a3ea-77ee44682c81)

**Comment by MrPurple6411** [comment]
@SanchozzDeponianin  ahh yes thank you :-) such small dumb mistake on my part. very sorry to have bothered you :-)
