### ISSUE TITLE
[Issue]: it seems like crash after building Mechanic Stationton is done

### ISSUE THREAD

**Issue by fruixs** [SanchozzDeponianin/ONIMods#73]
### Description of the bug/crash

it seems like crash after building Mechanic Stationton is done
disable this mod and no crash
```
NullReferenceException: Object reference not set to an instance of an object

IgnoreFetch.IgnoreFetchUtils.isFetchAllowed (Pickupable pickup, System.String chore, System.Boolean isArm) (at <cb6863303c8d4497871395099ba6ae53>:0)
IgnoreFetch.FetchChorePatch+<>c.<.cctor>b__5_0 (Chore+Precondition+Context& context, System.Object data) (at <cb6863303c8d4497871395099ba6ae53>:0)
Chore+Precondition+Context.RunPreconditions () (at <93e6d51e7c504f4483a782aaaf7248c3>:0)
Chore.CollectChores (ChoreConsumerState consumer_state, System.Collections.Generic.List`1[T] succeeded_contexts, System.Collections.Generic.List`1[T] failed_contexts, System.Boolean is_attempting_override) (at <93e6d51e7c504f4483a782aaaf7248c3>:0)
FetchChore.CollectChoresFromGlobalChoreProvider (ChoreConsumerState consumer_state, System.Collections.Generic.List`1[T] succeeded_contexts, System.Collections.Generic.List`1[T] failed_contexts, System.Boolean is_attempting_override) (at <93e6d51e7c504f4483a782aaaf7248c3>:0)
GlobalChoreProvider.CollectChores (ChoreConsumerState consumer_state, System.Collections.Generic.List`1[T] succeeded, System.Collections.Generic.List`1[T] failed_contexts) (at <93e6d51e7c504f4483a782aaaf7248c3>:0)
ChoreConsumer.FindNextChore (Chore+Precondition+Context& out_context) (at <93e6d51e7c504f4483a782aaaf7248c3>:0)
Brain.FindBetterChore (Chore+Precondition+Context& context) (at <93e6d51e7c504f4483a782aaaf7248c3>:0)
Brain.UpdateChores () (at <93e6d51e7c504f4483a782aaaf7248c3>:0)
Brain.UpdateBrain () (at <93e6d51e7c504f4483a782aaaf7248c3>:0)
MinionBrain.UpdateBrain () (at <93e6d51e7c504f4483a782aaaf7248c3>:0)
BrainScheduler+BrainGroup.RenderEveryTick (System.Single dt, System.Boolean isAsyncPathProbeEnabled) (at <93e6d51e7c504f4483a782aaaf7248c3>:0)
BrainScheduler.RenderEveryTick (System.Single dt) (at <93e6d51e7c504f4483a782aaaf7248c3>:0)
SimAndRenderScheduler+RenderEveryTickUpdater.Update (IRenderEveryTick updater, System.Single dt) (at <0a61a0e7beaf44b6b425814476821935>:0)
UpdateBucketWithUpdater`1[DataType].Update (System.Single dt) (at <0a61a0e7beaf44b6b425814476821935>:0)
StateMachineUpdater+BucketGroup.AdvanceOneSubTick (System.Single dt) (at <0a61a0e7beaf44b6b425814476821935>:0)
StateMachineUpdater.RenderEveryTick (System.Single dt) (at <0a61a0e7beaf44b6b425814476821935>:0)
Game.LateUpdate () (at <93e6d51e7c504f4483a782aaaf7248c3>:0)

Build: U52-623711-SC
```

### Steps To Reproduce

MOD LIST and Mod Preset Manager in JSON

[군단 09.json](https://github.com/user-attachments/files/16402748/09.json)

- Mod Updater
- Stock Bug Fix
- Help, none of my mod options are working after the DLC update - fix
- Mod Profile Manager
- Mod Preset Manager [MPM]
- Always Show Capacity
- Skills Retainer
- Eat every day
- 传送服 Teleport Suit
- AI Improvements
- Critter Shedding
- No Critter Overcrowding
- Efficient Supply
- Extra Moulding Skins
- Food Supply Tooltip
- Stats Unlimited
- Sweep By Type
- Auto Light Tile(自亮砖)
- Capsule 2.0
- Deselect New Materials
- Duplicant Stat Selector [DSS]
- MegaBattery
- Better Air Filters
- [DLC] Radiation Rebalanced
- Endless Science
- No Manual Delivery
- Demolish Neutronium
- Blood
- Sick Go To Med Bed
- Block Decor Effects Behind Walls
- Passive Gas Vent Input
- Plastic Utilities
- Better Deselect
- Butcher & Fishing Stations
- Falling Sand
- Wounded Go To Med Bed
- Steel Ladder
- Rebalanced Plant Mutations
- ConveyorTiles
- No Drop // by @Ony 
- Cluster Generation Manager [CGM]
- Plastic Mesh and Airflow Tiles
- Happy Digging: Dwarf Edition (Fixed)
- Enclosed Telescope Tune-Up
- Space POI Additional Info
- Gigawatt Wire
- Movable Features 位移信标
- Endless Telescope
- Big Storage
- Utility Glass
- Smelter
- Wall Pumps
- Control your Robots
- [Vanilla + DLC] Biobot Upgrades
- MutationFarmer
- Universal Electrolyzer
- Advanced Flow Management
- Automated Canisters Reloaded
- Pick up Flopping Pacu
- Shinebug Reactor
- 主动洗手 Active Hand Washing
- Portal Network
- Critter Traits
- Wrangle & Carry
- Bio-Inks: Rechargeable Printing Pods
- Research Queue
- Fixed Ore Scrubber
- Aquatic Farm
- Buildable Neural Vacillator
- Scan & Relay Satellites
- Configurable Timers
- Dupes Engineering
- Trash Cans
- Move This Here
- Daily Routine
- Rocketry Expanded
- Freezer
- Better Info Cards
- Better Farming Effects and Tweaks
- Packaged Bleach Stone
- More Plants
- Space Radiator
- Custom Reservoirs
- Sealed and Insulated Containers
- Queue For Sinks
- Sealed Pitcher Pump
- Planning Tool
- Bubbles Bathtub
- Plastic Door
- Self-sealing Airlocks Revived
- Workshop Profiles
- True Tiles
- Hysteresis Storage
- Rest for the Weary
- Insulated Radbolt Joint Plate
- Weeb Dupes
- Tiny Door
- Clothing Locker
- Squirrel Wheel
- Dupes Refrigeration
- Insulated Joint Plate
- Insulated Door
- Ribbed Fire Pole
- Decor Pack I
- Build Over Plants (식물 위에 건설)
- Show Building Ranges
- More Small Sculptures
- More Marble Sculptures
- Wild Planter Box
- Giant Doors
- 传送端口 (Transfer Port)
- Extended Building Width
- Geysers Automation Extension 间歇泉自动化扩展
- More Emotions
- [Vanilla + DLC] Rooms Expanded
- Mechanics Station
- AI Controlled Rockets
- 自然种植盒（Natural Plant Box）
- DuperyFixed
- NSHS MOD For Dupery
- MedicineExpanded
- Pip Plant Overlay
- Athletic Manual Generator
- Any Ice Liquefier
- Simpler Pip Plant Rule (Vanilla/DLC)
- Build Priority Keys
- Overjoy Chance Rebalanced
- Element Capture Capsule
- [Vanilla + DLC] 게임 진행 도우미+ V2.0
- Reapy Fixed
- Rotatable Radbolt Chamber Output
- Waste Not, Want Not
- Forbid Items
- Rebuildable AETN
- Stairs
- No Mop Limit
- The Golden Throne
- Missing Element Textures
- Asphalt Tile
- Attribute-based Workshop Restrictions
- Where's My Loot?
- Meteor Drops
- Radioactive Wheezeworts
- Asphalt Stairs / 柏油台阶
- Backwalls
- SaltBox 盐盒
- Germicidal Lamps
- Double Bed
- Scaffolds
- Festive Halloween Spices
- Storage Refrigerator Thresholds
- Sweepn't
- [Vanilla + DLC] 고급 발전기+ V2.0
- Echo and the Chaos Crew
- [Vanilla + DLC] More Logic Ports
- [Vanilla + DLC] 친환경 화장실 & 농사+ V3.0
- Auto Suit Delivery
- Crabs Profit
- Carousel
- Auto Remove Baby
- Grind Up Metals
- Smart Pumps
- Fluid Shipping
- Only Tame
- Artifacts in Care Packages
- Vitals Display Rads
- High Pressure Applications
- Graveyard Keeper
- RTGenerator
- Automation Bypass
- Debris Thermostat 碎片恒温器
- Balloon Dispenser
- Worn Suit doesn't drop Canister
- Smart Coolers
- Resource Sensor
- Thermo Sensor Tile
- Suit Recharger

Reproducing bug in save file
[군단 클래식 02 Cycle 40.zip](https://github.com/user-attachments/files/16402772/02.Cycle.40.zip)

1. build any room
2. there is two Rockcrucher in the room
3. build mechanic station in the room
For detail i attached sav file

[Player.log](https://github.com/user-attachments/files/16402739/Player.log)

### Player.log

[Player.log](https://github.com/user-attachments/files/16402794/Player.log)

**Comment by SanchozzDeponianin** [comment]
**_IgnoreFetch_** is not part of the Mechanic Station or any of my other mods.
Contact the author of the corresponding mod. **_Sweepn't_**, I suppose.

**Comment by fruixs** [comment]
Thank you for reply
