### ISSUE TITLE
[Issue]: The butcher station no longer counts babies for the room critter count

### ISSUE THREAD

**Issue by Lotan21** [SanchozzDeponianin/ONIMods#74]
### Description of the bug/crash

Since the latest patch the butcher station (and maybe fishing station too, did not test) no longer counts babies for the room critter count. This makes it inconsistent with the critter drop-off count a makes the stables constantly crowded unless babies are stored in different room.
Previously the butcher station counted both adult and baby critters.

### Steps To Reproduce

self explanatory from description

### Player.log

[Player.log](https://github.com/user-attachments/files/16433444/Player.log)

**Comment by SanchozzDeponianin** [comment]
it works as intended

> Update: 23 Feb  8:21am
Compatibility with the new U51 beta version of the game.
Now only the Creatures selected in the filter are counted, Similar to the new Critter Drop-Off.
Minor corrections to the codex and the build menu.

to return to the old behavior, turn off this checkbox
![457140_20240731095524_1](https://github.com/user-attachments/assets/6f0041aa-3912-4b06-854d-c94aef04a67a)
