### ISSUE TITLE
[Issue]: Butcher station no errands scheduled

### ISSUE THREAD

**Issue by luchillo17** [SanchozzDeponianin/ONIMods#76]
### Description of the bug/crash

I'm assuming here but probably an issue with another mod, `[Vanilla + DLC] Rooms Expanded` replaces the ranching room with `Agricultural Room`, in this case, the butcher station should detect the critters to be butchered but it doesn't do anything.

![Screenshot 2024-08-11 012239](https://github.com/user-attachments/assets/55680dc9-8893-4159-986f-a8ee9d246a44)

### Steps To Reproduce

1. Install mod `[Vanilla + DLC] Rooms Expanded` from steam's workshop.
2. Make a ranch and try to use the butcher station.

### Player.log

[Player.log](https://github.com/user-attachments/files/16571818/Player.log)

**Comment by SanchozzDeponianin** [comment]
I suppose your problem is that the Hatches don't have a path to the station.
Just deconstruct this door.

**Comment by luchillo17** [comment]
Wait really? I would have thought since the dupes can reach it the station should work, lemme try...

**Comment by luchillo17** [comment]
@SanchozzDeponianin My bad, you're totally correct, I thought it would schedule based on dupe's access, not critter reach, thanks for the prompt response.
