### ISSUE TITLE
[Issue]: Butcher Station don't count baby critters 

### ISSUE THREAD

**Issue by SuperR0ck** [SanchozzDeponianin/ONIMods#77]
### Description of the bug/crash

It's not a bug/crash, is more like a improvement. 
Inside a ranch room (max of 96 blocks) the maximum number of critters to br comfortable/happy and well reproduce are 8. 
I put the Butcher Station inside the ranch with Auto-Wrangle Surplus set to 8. 
Butcher Station do not consider baby critters when counting (baby critters are not in the list). So the room limit is be over the limit impacting the reproduction speed.
To fix the issue, the Butcher Station needs to count both adult and the baby critters (in my case I had both of the same type).
Thanks.

### Steps To Reproduce

Create a ranch room, put 6 adult critters and 4 baby critters inside. Set Auto-Wrangle Surplus to 8. Nothing will happen. 
If you put a Critter sensor with both adult and baby critter selected, the account will be 10.
![image](https://github.com/user-attachments/assets/c5668386-839d-4f83-8808-1ddc6d3350ce)

![image](https://github.com/user-attachments/assets/03496a04-e7d0-4fe9-b584-c1fbe8ef687c)

### Player.log

[Player.log](https://github.com/user-attachments/files/16632905/Player.log)

**Comment by SanchozzDeponianin** [comment]
it works as intended

> Update: 23 Feb  8:21am
Compatibility with the new U51 beta version of the game.
Now only the Creatures selected in the filter are counted, Similar to the new Critter Drop-Off.
Minor corrections to the codex and the build menu.

to return to the old behavior, turn off this checkbox
![457140_20240731095524_1](https://github.com/user-attachments/assets/6f0041aa-3912-4b06-854d-c94aef04a67a)

**Comment by SuperR0ck** [comment]
It worked!
I would suggest add a small note in steam workshop to help noob players like myself. :)
Thanks!!!
