### ISSUE TITLE
[Translation]: SPANISH / ESPAÑOL - "No Manual Delivery" and "Squirrel Generator"

### ISSUE THREAD

**Issue by edubistkrank** [SanchozzDeponianin/ONIMods#79]
### What mod is that translation for?

Not listed (use textfield below)

### Additional Comments

Spanish translations for "No Manual Delivery" and "Squirrel Generator"

.- edubistkrank -.

### translation file

[NoManualDelivery-SquirrelGenerator_ES.zip](https://github.com/user-attachments/files/17056466/NoManualDelivery-SquirrelGenerator_ES.zip)

**Comment by SanchozzDeponianin** [comment]
Thank you for contributing new translations.
