### ISSUE TITLE
[Issue]: Butcher and fishing stations miscount the critters in stable and aquarium, I use rooms expanded mod

### ISSUE THREAD

**Issue by Jimzawy** [SanchozzDeponianin/ONIMods#81]
### Description of the bug/crash

The butcher and fishing stations are not working as intended and not counting critters properly for auto wrangle surplus 

### Steps To Reproduce

![prob 1](https://github.com/user-attachments/assets/4de1fd1b-6e08-4f2c-b427-c164aaa34142)
![prob 2](https://github.com/user-attachments/assets/acc58ef9-9615-4e29-a14b-89014bed21cb)
![prob 3](https://github.com/user-attachments/assets/acca5b0e-ddcf-439c-965d-f40b72198e7a)

### Player.log

[Player.log](https://github.com/user-attachments/files/17267685/Player.log)

**Comment by SanchozzDeponianin** [comment]
it works as intended

> Update: 23 Feb  8:21am
Compatibility with the new U51 beta version of the game.
Now only the Creatures selected in the filter are counted, Similar to the new Critter Drop-Off.
Minor corrections to the codex and the build menu.

to return to the old behavior, turn off this checkbox
![457140_20240731095524_1](https://github.com/user-attachments/assets/6f0041aa-3912-4b06-854d-c94aef04a67a)
