### ISSUE TITLE
[Issue]: crash

### ISSUE THREAD

**Issue by JNDK9119** [SanchozzDeponianin/ONIMods#82]
### Description of the bug/crash

Enable mod Rover Recharger. Attempt to build crashed game. Used Modupdater. Attempt to build crashed game. 3rd try did not try building but game crashed when I clicked on rover lander. Unload mod and game runs. 

### Steps To Reproduce

Add mod to ONI Spaced Out. 
Load game. 
Try to build recharger.
Crash. Sometimes immediately. Sometimes after a few minutes.

### Player.log

[Player.log](https://github.com/user-attachments/files/17345086/Player.log)
[ONI rover recharger crash.txt](https://github.com/user-attachments/files/17345088/ONI.rover.recharger.crash.txt)

**Comment by SanchozzDeponianin** [comment]
The attached log file indicates that the crash was caused by some third-party mod that adds additional buttons to the buildings side screen, and this mod is seriously outdated. 
I can't say more precisely what mod it is.

**Comment by JNDK9119** [comment]
Yes it appears it is different than I thought. Not sure why it appeared after I added the recharger mod. Sorry to bother you. Hoping I will get it sorted and be able to use your mod.

**Comment by JNDK9119** [comment]
Looks like this is the culprit. Removed. Once again, sorry for the bother. Thanks for the quick response. https://steamcommunity.com/sharedfiles/filedetails/?id=2021224960
