### ISSUE TITLE
[Issue]: BionicDupe Can't Use Mechanics Station

### ISSUE THREAD

**Issue by Koamasi** [SanchozzDeponianin/ONIMods#88]
### Description of the bug/crash

Bionic Dupes can't use Mechanics Station even if they have machinery  booster.

### Steps To Reproduce

Just create a Bionic Dupe with machinery booster and a Machine Stop.

### Player.log

There is no crash in my game.

**Comment by SanchozzDeponianin** [comment]
fixed in 1.4.1 mod version
